'''
Problem 2: Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

def get_even_number_fibonacci_sum(max_num):
    prev_num = 1
    cur_num = 2
    fibo_sum = 2

    while (cur_num < max_num):
        sum_num = prev_num + cur_num;
        fibo_sum += sum_num if sum_num % 2 == 0 else 0
        prev_num = cur_num
        cur_num = sum_num
    
    return fibo_sum

max_num = 4000000
print get_even_number_fibonacci_sum(max_num)